"""empty message

Revision ID: 90e83d6bd36d
Revises: 4a92c7305564
Create Date: 2019-06-12 08:37:36.806531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e83d6bd36d'
down_revision = '4a92c7305564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('endtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'endtime')
    # ### end Alembic commands ###
